# Generated by Django 5.2.12 on 2026-05-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bath', 'Bath'), ('clothing', 'Clothing'), ('toys', 'Toys'), ('diapers', 'Diapers')], default='bath', max_length=50),
            preserve_default=False,
        ),
    ]
