# Generated by Django 5.2.12 on 2026-05-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bath', 'Bath'), ('clothing', 'Clothing'), ('toys', 'Toys'), ('diapers', 'Diapers'), ('bedding', 'Bedding'), ('feeding', 'Feeding'), ('essential', 'Essential')], max_length=50),
        ),
    ]
