# Generated by Django 5.2.12 on 2026-05-20 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bath', 'Bath'), ('clothing', 'Clothing'), ('toys', 'Toys'), ('diapers', 'Diapers'), ('bedding', 'Bedding'), ('feeding', 'Feeding'), ('essential', 'Essential'), ('bottles', 'Bottles'), ('nightwear', 'Nightwear')], max_length=50),
        ),
    ]
