# Generated by Django 5.2.12 on 2026-05-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cartitem_user_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bath', 'Bath'), ('clothes', 'Clothes'), ('toys', 'Toys'), ('diapers', 'Diapers'), ('bedding', 'Bedding'), ('feeding', 'Feeding'), ('essential', 'Essential'), ('bottles', 'Bottles'), ('nightwear', 'Nightwear')], max_length=50),
        ),
    ]
